<?php

namespace Elephanto\Http;

use Elephanto\Contracts\Request as RequestInterface;
use Elephanto\Exception\HttpException;

/**
 * Defines a HTTP Request.
 *
 * @author Salomon Dion (dev.mrdion@gmail.com)
 */
class Request implements RequestInterface
{
    use Body;

    /**
     * Request options.
     *
     * @var array
     */
    private $requestOptions;

    /**
     * Request response.
     *
     * @var Response
     */
    private $response;

    /**
     * Curl resource.
     *
     * @var resource
     */
    private $ch;

    public function __construct(array $requestOptions)
    {
        $this->requestOptions = $requestOptions;
    }

    /**
     * Execute the request.
     *
     * @return $this
     */
    public function run(): Request
    {
        $this->initializeCurl();
        $this->setCurlOptions();

        $data = curl_exec($this->ch);

        if (false === $data) {
            throw new HttpException(curl_error($this->ch));
        }

        $curlInfos = curl_getinfo($this->ch);

        $this->response = (new Response($data, new Headers([
            'Content-Type' => $curlInfos['content_type'],
            'url' => $curlInfos['url'],
            'Host' => $curlInfos['primary_ip'],
            'status' => $curlInfos['http_code'],
        ])))->setRequest($this);

        $this->close();

        return $this;
    }

    /**
     * Return the response generated by the request.
     */
    public function response(): Response
    {
        return $this->response;
    }

    /**
     * Return the headers of the request.
     */
    public function headers(): Headers
    {
        return new Headers($this->requestOptions['headers']);
    }

    /**
     * Return the URL of the request.
     */
    public function url(): string
    {
        return $this->requestOptions['url'];
    }

    protected function data()
    {
        $body = $this->requestOptions['body'] ?? null;

        return  $body ? json_encode($this->requestOptions['body']) : null;
    }

    private function setCurlOptions()
    {
        curl_setopt_array($this->ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_BINARYTRANSFER => true,
            CURLOPT_HTTPHEADER => $this->requestOptions['headers'],
        ]);

        if ('POST' === $this->requestOptions['method']) {
            curl_setopt($this->ch, CURLOPT_POST, true);
            curl_setopt($this->ch, CURLOPT_POSTFIELDS, json_encode($this->requestOptions['body']));
        }
    }

    /**
     * Ensures that the curl resource has been initialized.
     *
     * @param string $url
     */
    private function initializeCurl()
    {
        if (!is_resource($this->ch)) {
            $this->ch = curl_init($this->requestOptions['url']);
        }
    }

    /**
     * Close connection.
     */
    private function close()
    {
        if (is_resource($this->ch)) {
            curl_close($this->ch);
            $this->ch = null;
        }
    }
}
